FROM node:20-bookworm-slim AS base
ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH
RUN corepack enable && corepack prepare pnpm@10.13.1 --activate

FROM base AS dependencies
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

FROM base AS builder
WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .
ARG NEXT_PUBLIC_COLLECTOR_PROXY_BASE_URL
ARG NEXT_PUBLIC_COLLECTOR_BRIDGE_DEBUG=0
ARG NEXT_PUBLIC_SOURCE_CODE_URL
ARG NEXT_PUBLIC_SOURCE_REVISION
ENV NEXT_PUBLIC_COLLECTOR_PROXY_BASE_URL=$NEXT_PUBLIC_COLLECTOR_PROXY_BASE_URL
ENV NEXT_PUBLIC_COLLECTOR_BRIDGE_DEBUG=$NEXT_PUBLIC_COLLECTOR_BRIDGE_DEBUG
ENV NEXT_PUBLIC_SOURCE_CODE_URL=$NEXT_PUBLIC_SOURCE_CODE_URL
ENV NEXT_PUBLIC_SOURCE_REVISION=$NEXT_PUBLIC_SOURCE_REVISION
RUN pnpm build

FROM node:20-bookworm-slim AS runner
WORKDIR /app
ARG NEXT_PUBLIC_COLLECTOR_PROXY_BASE_URL
ARG NEXT_PUBLIC_COLLECTOR_BRIDGE_DEBUG=0
ARG NEXT_PUBLIC_SOURCE_CODE_URL
ARG NEXT_PUBLIC_SOURCE_REVISION
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV COLLECTOR_ONLY_MODE=1
ENV COLLECTOR_PROXY_ENABLED=1
ENV NEXT_PUBLIC_COLLECTOR_PROXY_BASE_URL=$NEXT_PUBLIC_COLLECTOR_PROXY_BASE_URL
ENV NEXT_PUBLIC_COLLECTOR_BRIDGE_DEBUG=$NEXT_PUBLIC_COLLECTOR_BRIDGE_DEBUG
ENV NEXT_PUBLIC_SOURCE_CODE_URL=$NEXT_PUBLIC_SOURCE_CODE_URL
ENV NEXT_PUBLIC_SOURCE_REVISION=$NEXT_PUBLIC_SOURCE_REVISION
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
USER node
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:3000/collector/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"
CMD ["node", "server.js"]
